/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.51).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.vu.localhost.poss.service.controller;

import com.vu.localhost.poss.service.model.Service;
import com.vu.localhost.poss.service.model.CreateService;
import com.vu.localhost.poss.service.model.CreateServiceBooking;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-12-25T04:32:42.344389+02:00[Europe/Vilnius]")
@Validated
public interface ServiceApi {

        @Operation(summary = "Create a new service offering", description = "Creates a new service offering in the POS system.", security = {
                        @SecurityRequirement(name = "BearerAuth") }, tags = { "service" })
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "201", description = "service created successfully"),

                        @ApiResponse(responseCode = "400", description = "Invalid input") })
        @RequestMapping(value = "/service", consumes = { "application/json" }, method = RequestMethod.POST)
        ResponseEntity<Service> createService(
                        @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CreateService body);

        @Operation(summary = "Create a new booking for a service", description = "Schedules a new booking for a specified service.", security = {
                        @SecurityRequirement(name = "BearerAuth") }, tags = { "Booking" })
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "201", description = "Booking created"),

                        @ApiResponse(responseCode = "400", description = "Invalid input") })
        @RequestMapping(value = "/service/{serviceId}/booking", consumes = {
                        "application/json" }, method = RequestMethod.POST)
        ResponseEntity<Void> createServiceBooking(
                        @Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("serviceId") Long serviceId,
                        @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CreateServiceBooking body);

        @Operation(summary = "Remove a service offering", description = "Deletes a specific service offering from the POS system.", security = {
                        @SecurityRequirement(name = "BearerAuth") }, tags = { "service" })
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "204", description = "service deleted successfully"),

                        @ApiResponse(responseCode = "404", description = "service not found") })
        @RequestMapping(value = "/service/{serviceId}", method = RequestMethod.DELETE)
        ResponseEntity<Void> deleteService(
                        @Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("serviceId") Long serviceId);

        @Operation(summary = "Retrieve detailed information about a specific service", description = "Retrieves detailed information about a specific service, including availability and pricing.", security = {
                        @SecurityRequirement(name = "BearerAuth") }, tags = { "service" })
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "Detailed service information", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Service.class))),

                        @ApiResponse(responseCode = "404", description = "service not found") })
        @RequestMapping(value = "/service/{serviceId}", produces = { "application/json" }, method = RequestMethod.GET)
        ResponseEntity<Service> getServiceDetails(
                        @Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("serviceId") Long serviceId);

        @Operation(summary = "Update details of an existing service", description = "Updates details of an existing service offering.", security = {
                        @SecurityRequirement(name = "BearerAuth") }, tags = { "service" })
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "service updated successfully"),

                        @ApiResponse(responseCode = "400", description = "Invalid input"),

                        @ApiResponse(responseCode = "404", description = "service not found") })
        @RequestMapping(value = "/service/{serviceId}", consumes = { "application/json" }, method = RequestMethod.PUT)
        ResponseEntity<Service> updateService(
                        @Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("serviceId") Long serviceId,
                        @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CreateService body);

}
